fix: Render menu lists in a React portal by default
Doist/reactist pull request #619
Opened 2022-01-12 14:57 UTC by gnapse

## Short description

This PR changes menu popovers so that, by default, they render in a React portal, rather than by the side of the trigger button position in the DOM.

The change in this PR was motivated by a specific issue in Twist (https://github.com/Doist/Issues/issues/4239), where the fix is to make the menu render in a portal. This can be achieved in app code without changing Reactist, by passing the `modal={true}` prop to the top-level `Menu` (i.e. `<Menu modal={true}>`).

However, I think that it is saner to make this the default, as in general, floating elements are better off being rendered near the root of the DOM. Among the reasons, for instance, is the fact that while in a deeper part of the DOM, they could inherit unwanted CSS that affects the way they look.

From [reakit's menu component documentation](https://reakit.io/docs/menu/), these below are the implications of rendering menus in this way, that are IMO also ok and even desired:

> `preventBodyScroll` is automatically enabled, focus is trapped within the dialog and the dialog is rendered within a `Portal` by default.

BTW, this change is not preventing consumers of our menu component from reverting to a non-portal menu if they so wish. They can always do so via `<Menu modal={false}>`.

Last, but not least: doing this required upgrading the Reakit version to the latest, because the menu positioning while in this portal mode was not working correctly, but in the latest version it does.

## Test plan

- Run storybook
    - [ ] see that menus work as usual.
- Run twist-web while linked to Reactist locally (`ide twist-web run --link-reactist`), making sure that you have the reactist repo checked out locally at this branch, and you run `npm run start` in that repo folder too.
    - [ ] Try out various menus all around Twist and see that they work.

## PR Checklist

-   [ ] Added tests for bugs / new features
-   [ ] Updated docs (storybooks, readme)
-   [ ] Executed `npm run validate` and made sure no errors / warnings were shown
-   [ ] Described changes in `CHANGELOG.md`
-   [ ] Bumped version in `package.json` and `package-lock.json` (`npm --no-git-tag-version version <major|minor|patch>`) [ref](https://docs.npmjs.com/cli/v6/commands/npm-version)
-   [ ] Updated all static build artifacts (`npm run build-all`)

## Versioning

2022-01-13 12:20 UTC, jvalente commented
When clicking outside to dismiss the thread list item menu, it looks like it bubbles the click event to the thread link. 
It behaves as if the thread link was clicked.

https://user-images.githubusercontent.com/40036/149329146-634b680d-bd81-4d1d-aac6-2f709b50927c.mp4

2022-01-13 13:31 UTC, jvalente requested changes
.

2022-01-14 11:15 UTC, gnapse commented
@jvalente you should be able to get it working correctly now, using the latest version of twist-web (make sure to pull as this depends on PR that I just merged).

2022-01-14 11:38 UTC, jvalente commented
hello @gnapse ! In some occasions, specifically on the the thread list items, the menu renders on the top left. The click issue I described above is gone.

https://user-images.githubusercontent.com/40036/149509620-0e9ead38-01a9-4e02-8809-be219e907f9d.mp4

2022-01-14 11:57 UTC, gnapse commented
Hmmm, thanks anyway @jvalente. I'll dig in more on this.

2022-01-14 12:02 UTC, jvalente commented
Ok @gnapse let me know if you need any help debugging. Will request changes to cleanup my pending reviews list. Please re-request when suitable.

2022-01-14 12:02 UTC, jvalente requested changes
.

2022-02-23 23:22 UTC, gnapse commented
Closing this as it's superseded by #635 (which also started off with the left foot, and seems to be doomed to be closed without merging too 😕)

2022-02-23 23:22 UTC, closed without merging